#based on https://github.com/Hoikas/PlasmaPrefix/blob/681287437d022a8fb9e4560c3a41a8ab2cb71b54/appveyor.yml
version: '{build}'

image:
  - Visual Studio 2022

build_script:
  - ps: |
      $outpath = (Get-Location).Path
      Set-Location C:\tools\vcpkg
      git pull 2> $null
      bootstrap-vcpkg.bat
      Add-Content -Path C:\tools\vcpkg\triplets\x64-windows-static.cmake -Value "set(VCPKG_BUILD_TYPE `"release`")" -NoNewline
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }
      vcpkg install openssl:x64-windows-static

      mkdir c:\src\
      Set-Location c:\src
      git clone --depth=1 https://github.com/nmap/nmap
      set-location c:\src\nmap\mswin32
      msbuild nmap.sln
      
#     Set-Location installed\x64-windows-static\tools\openssl
#     7z a $outpath\openssl.zip openssl.exe

#artifacts:
# - path: openssl.zip
